/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SnapRouteImport } from './routes/snap'
import { Route as VanityRouteImport } from './routes/vanity'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapRoute = SnapRouteImport.update({
  id: '/snap',
  path: '/snap',
  getParentRoute: () => rootRouteImport,
} as any)
const VanityRoute = VanityRouteImport.update({
  id: '/vanity',
  path: '/vanity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/snap': typeof SnapRoute
  '/vanity': typeof VanityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/snap': typeof SnapRoute
  '/vanity': typeof VanityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/snap': typeof SnapRoute
  '/vanity': typeof VanityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat' | '/scan' | '/settings' | '/snap' | '/vanity'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat' | '/scan' | '/settings' | '/snap' | '/vanity'
  id: '__root__' | '/' | '/chat' | '/scan' | '/settings' | '/snap' | '/vanity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  SnapRoute: typeof SnapRoute
  VanityRoute: typeof VanityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snap': {
      id: '/snap'
      path: '/snap'
      fullPath: '/snap'
      preLoaderRoute: typeof SnapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vanity': {
      id: '/vanity'
      path: '/vanity'
      fullPath: '/vanity'
      preLoaderRoute: typeof VanityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  SnapRoute: SnapRoute,
  VanityRoute: VanityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
